name: Generate GitHub Trophy SVG

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Trophy SVG
        run: |
          mkdir -p output
          curl -s "https://github-profile-trophy.vercel.app/?username=TranVanTu2k5&theme=onedark&column=6" -o output/trophy.svg

      - name: Commit and Push Trophy SVG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update GitHub Trophy SVG"
          file_pattern: "output/trophy.svg"
